INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (1, 11, 'PXR4 1', 100, 0, 11, 11,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (1, 1, 20);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (2, 1, 21);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (2, 11, 'PXR4 2', 101, 0, 26, 11,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (3, 2, 20);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (4, 2, 21);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (3, 11, 'PXR4 3', 102, 0, 29, 11,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (5, 3, 20);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (6, 3, 21);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (4, 10, 'NA', 202, 5, 9, 9,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (7, 4, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (8, 4, 11);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (5, 10, 'NA', 404, 1, 12, 13,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (9, 5, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (10, 5, 11);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (11, 5, 12);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (12, 5, 13);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (13, 5, 14);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (6, 10, 'NA', 387, 1, 12, 14,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (14, 6, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (15, 6, 11);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (7, 10, 'NA', 388, 1, 13, 13,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (16, 7, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (17, 7, 11);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (8, 10, 'NA', 391, 1, 13, 14,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (18, 8, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (19, 8, 11);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (9, 10, 'NA', 346, 1, 30, 13,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (20, 9, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (21, 9, 11);
INSERT INTO device (id, device_type_id, name, address, port, bin_id, bin_section_id,year) VALUES (10, 10, 'NA', 312, 1, 30, 14,2012);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (22, 10, 10);
INSERT INTO sensor (id, device_id, sensor_type_id) VALUES (23, 10, 11);
